# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lettre-digital-carnet',
                'doc_host': 'https://grasshoff.github.io',
                'git_url': 'https://github.com/grasshoff/lettre-digital-carnet',
                'lib_path': 'lettre_digital_carnet'},
  'syms': {'lettre_digital_carnet.core': {'lettre_digital_carnet.core.foo': ('core.html#foo', 'lettre_digital_carnet/core.py')}}}